<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta content="IE=edge" http-equiv="X-UA-Compatible">';
echo '<meta content="width=device-width,initial-scale=1" name="viewport">';
echo '<meta content="description" name="description">';
echo '<meta name="google" content="notranslate" />';
echo '<meta content="Mashup templates have been developped by Orson.io team" name="author">';
echo '';
echo '<!-- Disable tap highlight on IE -->';
echo '<meta name="msapplication-tap-highlight" content="no">';
echo '';
echo '<link rel="apple-touch-icon" sizes="180x180" href="./assets/apple-icon-180x180.png">';
echo '<link href="./assets/favicon.ico" rel="icon">';
echo '';
echo '<title>ABHIRAM portfolio</title>';
echo '';
echo '<link href="./main.3f6952e4.css" rel="stylesheet"></head>';
echo '';
echo '<body class="minimal">';
echo '<div id="site-border-left"></div>';
echo '<div id="site-border-right"></div>';
echo '<div id="site-border-top"></div>';
echo '<div id="site-border-bottom"></div>';
echo '<!-- Add your content of header -->';
echo '<header>';
echo '<nav class="navbar  navbar-fixed-top navbar-inverse">';
echo '<br>';
echo '<br> <br>';
echo '<br>';
echo '';
echo '<div class="container">';
echo '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">';
echo '<span class="sr-only">Toggle navigation</span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '</button>';
echo '';
echo '<div class="collapse navbar-collapse" id="navbar-collapse">';
echo '<ul class="nav navbar-nav ">';
echo '<li><a href="./index.html" title="">01 : Home</a></li>';
echo '<li><a href="./works.html" title="">02 : Works</a></li>';
echo '<li><a href="./about.html" title="">03 : About me</a></li>';
echo '<li><a href="./contact.html" title="">04 : Contact</a></li>';
echo '<li><a href="./components.html" title="">05 : Components</a></li>';
echo '</ul>';
echo '';
echo '';
echo '</div>';
echo '</div>';
echo '</nav>';
echo '</header>';
echo '<!-- Add your site or app content here -->';
echo '';
echo '';
echo '<div class="hero-full-container background-image-container white-text-container" style="background-image: url('space.jpg')">';
echo '<div id="background-wrap">';
echo '<div class="bubble x1"></div>';
echo '<div class="bubble x2"></div>';
echo '<div class="bubble x3"></div>';
echo '<div class="bubble x4"></div>';
echo '<div class="bubble x5"></div>';
echo '<div class="bubble x6"></div>';
echo '<div class="bubble x7"></div>';
echo '<div class="bubble x8"></div>';
echo '<div class="bubble x9"></div>';
echo '<div class="bubble x10"></div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-xs-12">';
echo '<div class="hero-full-wrapper">';
echo '<div class="text-content">';
echo '<h1>Hello,<br>';
echo '<span id="typed-strings">';
echo '<span>I'm ABHIRAM<br>KRISHNA</span>';
echo '<span>GRAPHIC Designer</span>';
echo '<span>FRONT Dev</span>';
echo '<span>Freelance</span>';
echo '</span>';
echo '<span id="typed"></span>';
echo '</h1>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '';
echo '<script>';
echo 'document.addEventListener("DOMContentLoaded", function (event) {';
echo 'type();';
echo 'movingBackgroundImage();';
echo '});';
echo '</script>';
echo '';
echo '';
echo '<script type="text/javascript" src="./main.70a66962.js"></script></body>';
echo '';
echo '</html>';
?>
